/**
 * Deep Research Orchestrator
 *
 * Coordinates multi-round research using specialized services.
 */

import type { ExtensionContext } from '@mariozechner/pi-coding-agent';
import { type Model } from '@mariozechner/pi-ai';
import { Type, type Static } from 'typebox';
import { logger } from '../logger.ts';
import { metrics } from '../utils/metrics.ts';
import {
  getMaxRounds,
} from '../core/planning-utils.ts';
import type {
  ResearchObserver,
} from './research-observer.ts';
import {
  getResearchSynthesisService,
  cleanupResearchServices,
  resetResearchServices,
} from './research-session-manager.ts';
import {
  ServiceNames,
} from '../core/service-interfaces.ts';
import { getService } from '../core/service-registry.ts';
import { getConfig } from '../config.ts';
import type { Config } from '../config.ts';
import type { PlanningService } from '../core/planning-service.ts';
import type { IResearchOrchestration } from '../core/service-interfaces.ts';

/**
 * Schema for the research plan generated by the AI
 */
export const ResearchPlanSchema = Type.Object({
    action: Type.Optional(Type.Union([Type.Literal('delegate'), Type.Literal('synthesize'), Type.Literal('wait')])),
    researchers: Type.Optional(Type.Array(Type.Object({
        id: Type.String(),
        name: Type.String(),
        goal: Type.String(),
        queries: Type.Array(Type.String()),
        role: Type.Optional(Type.String())
    }))),
    allQueries: Type.Optional(Type.Array(Type.String())),
    content: Type.Optional(Type.String())
});

export type ResearchPlan = Static<typeof ResearchPlanSchema>;

export interface DeepResearchOrchestratorOptions {
  ctx: ExtensionContext;
  model: Model<any>;
  query: string;
  complexity: 1 | 2 | 3;
  sessionId: string;
  researchId: string;
  observer?: ResearchObserver;
  config?: Config;
  orchestrationService?: IResearchOrchestration;
}

/**
 * Deep Research Orchestrator
 *
 * Coordinates multi-round research using specialized services.
 */
export class DeepResearchOrchestrator {
  private currentRound = 0;
  private startTime: number = Date.now();
  private config: Config;
  private readonly sessionStart: number = Date.now();
  private orchestrationService: IResearchOrchestration | null = null;

  constructor(private options: DeepResearchOrchestratorOptions) {
    this.config = options.config || getConfig();
    if (options.orchestrationService) {
      this.orchestrationService = options.orchestrationService;
    }
  }

  private async getOrchestrationService(): Promise<IResearchOrchestration> {
    if (this.orchestrationService) return this.orchestrationService;
    this.orchestrationService = await getService<IResearchOrchestration>(ServiceNames.RESEARCH_ORCHESTRATION);
    return this.orchestrationService;
  }

  private async getPlanningService(): Promise<PlanningService> {
    return await getService<PlanningService>(ServiceNames.PLANNING);
  }

  private elapsed(): string {
    const s = Math.round((Date.now() - this.startTime) / 1000);
    return `+${s}s`;
  }

  /**
   * Run the multi-round research loop
   */
  async run(signal?: AbortSignal): Promise<string> {
    // Reset services for this research run
    await resetResearchServices();
    const { model, query, complexity, researchId, observer } = this.options;
    const orchestrationService = await this.getOrchestrationService();
    const planningService = await this.getPlanningService();

    logger.log(`[DeepOrchestrator] Starting multi-round research (complexity ${complexity}) for: "${query}"`);
    metrics.increment('research_sessions_total', 1, { mode: 'deep', complexity: String(complexity) });

    const maxRounds = getMaxRounds(complexity);

    try {
      while (this.currentRound < maxRounds) {
        if (signal?.aborted) throw new Error('Research aborted');
        this.currentRound++;
        this.startTime = Date.now();

        logger.log(`[DeepOrchestrator] Round ${this.currentRound}/${maxRounds} ${this.elapsed()}`);
        observer?.onRoundStart?.(this.currentRound);

        // Check infrastructure health
        const healthy = await orchestrationService.checkHealth(this.currentRound, researchId);
        if (!healthy && this.currentRound > 1) {
            logger.warn(`[DeepOrchestrator] Infrastructure unhealthy at Round ${this.currentRound}, attempting to continue with existing data...`);
        }

        // 1. Update/Generate Plan
        const synthesisService = await getResearchSynthesisService();
        const plan = await planningService.updatePlanForRound({
            query: query,
            complexity,
            round: this.currentRound,
            model,
            reports: synthesisService.getAllReports(),
            previousPlan: null,
            totalResearchersPlanned: planningService.getTotalResearchersPlanned(),
            signal
        });

        if (plan.action === 'synthesize' || this.currentRound >= maxRounds) {
            logger.log(`[DeepOrchestrator] Synthesis phase reached at Round ${this.currentRound} ${this.elapsed()}`);
            break;
        }

        if ((plan.action as any) === 'wait') {
            logger.log(`[DeepOrchestrator] AI requested wait, retrying Round ${this.currentRound} in 5s...`);
            await new Promise(r => setTimeout(r, 5000));
            this.currentRound--; // Retry this round
            continue;
        }

        // 2. Search Phase (if queries generated)
        let researcherLinks: Map<string, string[]> | undefined;
        if (plan.allQueries && plan.allQueries.length > 0) {
            const results = await orchestrationService.runSearchBurst(plan.allQueries, this.config, signal, (links: number) => {
                observer?.onSearchProgress?.(links);
            });
            researcherLinks = await orchestrationService.distributeSearchResults(plan, results);
        }

        // 3. Researcher Phase
        if (plan.researchers && plan.researchers.length > 0) {
            await orchestrationService.runResearchers({
                plan,
                options: this.options,
                currentRound: this.currentRound,
                signal
            }, researcherLinks);
        }

        // 4. Store synthesized descriptions for semantic search
        await orchestrationService.storeLinkDescriptions(this.currentRound, researchId, this.config);
      }

      // Final Synthesis
      logger.log(`[DeepOrchestrator] Final synthesis ${this.elapsed()}`);
      observer?.onRoundStart?.(maxRounds + 1); // Progress indicator for synthesis

      const synthesisServiceFinal = await getResearchSynthesisService();
      const finalReport = await planningService.updatePlanForRound({
          query: query,
          complexity,
          round: maxRounds, // Force synthesis
          model,
          reports: synthesisServiceFinal.getAllReports(),
          previousPlan: null,
          totalResearchersPlanned: planningService.getTotalResearchersPlanned(),
          mustSynthesize: true,
          signal
      });

      const result = finalReport.content || 'Research completed but no summary was generated.';
      const sessionDuration = Date.now() - this.sessionStart;
      metrics.observe('research_session_duration_ms', sessionDuration, { mode: 'deep', complexity: String(complexity), status: 'success' });
      
      return result;

    } catch (error) {
      const sessionDuration = Date.now() - this.sessionStart;
      metrics.observe('research_session_duration_ms', sessionDuration, { mode: 'deep', complexity: String(complexity), status: 'error' });
      logger.error(`[DeepOrchestrator] Research failed: ${error instanceof Error ? error.message : String(error)}`);
      throw error;
    } finally {
      await cleanupResearchServices();
    }
  }
}
