brand:
  docs_url: https://docs.searxng.org/
  issue_url: https://github.com/searxng/searxng/issues
  new_issue_url: https://github.com/searxng/searxng/issues/new
  public_instances: https://searx.space
  wiki_url: https://github.com/searxng/searxng/wiki
default_doi_resolver: oadoi.org
doi_resolvers:
  doi.org: https://doi.org/
  oadoi.org: https://oadoi.org/
engines:
- engine: duckduckgo
  name: duckduckgo
  shortcut: ddg
  timeout: 2.0
- categories:
  - general
  engine: brave
  name: brave
  shortcut: brv
- engine: bing
  name: bing
  shortcut: bi
- engine: wikipedia
  name: wikipedia
  shortcut: wp
  weight: 1.5
- categories:
  - images
  ddg_category: images
  engine: duckduckgo_extra
  name: duckduckgo images
  shortcut: ddi
- categories:
  - images
  engine: bing_images
  name: bing images
  shortcut: bii
- categories:
  - news
  ddg_category: news
  engine: duckduckgo_extra
  name: duckduckgo news
  shortcut: ddn
- categories:
  - news
  engine: bing_news
  name: bing news
  shortcut: bin
- categories:
  - videos
  ddg_category: videos
  engine: duckduckgo_extra
  name: duckduckgo videos
  shortcut: ddv
- categories:
  - videos
  engine: bing_videos
  name: bing videos
  shortcut: biv
- categories:
  - it
  engine: stackoverflow
  name: stackoverflow
  shortcut: so
- categories:
  - science
  engine: arxiv
  name: arxiv
  shortcut: arx
  weight: 1.5
- categories:
  - science
  engine: semantic_scholar
  name: semantic scholar
  shortcut: sem
  weight: 1.5
general:
  contact_url: false
  debug: false
  enable_metrics: false
  instance_name: pi SearXNG
  open_metrics: ''
  privacypolicy_url: false
outgoing:
  enable_http2: false
  extra_proxy_timeout: 10
  max_request_timeout: 30.0
  pool_connections: 150
  pool_maxsize: 20
  proxies:
    all://:
    - socks5://127.0.0.1:9150
  request_timeout: 10.0
  retries: 2
  useragent_suffix: ''
  using_tor_proxy: false
search:
  autocomplete: ''
  autocomplete_min: 4
  ban_time_on_fail: 5
  default_lang: en-US
  favicon_resolver: ''
  formats:
  - html
  - json
  - csv
  - rss
  max_ban_time_on_fail: 120
  safe_search: 0
  suspended_times:
    SearxEngineAccessDenied: 180
    SearxEngineCaptcha: 3600
    SearxEngineTooManyRequests: 180
    cf_SearxEngineAccessDenied: 86400
    cf_SearxEngineCaptcha: 1296000
    recaptcha_SearxEngineCaptcha: 604800
server:
  base_url: false
  bind_address: 0.0.0.0
  default_http_headers:
    Referrer-Policy: no-referrer
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
  http_protocol_version: '1.0'
  image_proxy: false
  limiter: false
  method: POST
  port: 8080
  public_instance: false
  secret_key: ''
ui:
  center_alignment: false
  default_locale: ''
  default_theme: simple
  hotkeys: default
  query_in_title: false
  results_on_new_tab: false
  search_on_category_select: true
  static_path: ''
  templates_path: ''
  theme_args:
    simple_style: auto
  url_formatting: pretty
